### ISSUE TITLE
docker-compose file for vmc-docker

### ISSUE THREAD

**Issue by jonathangull** [DSecureMe/vmc-docker#12]
Hi 

Can you please share docker-compose file for vmc-docker project. Having hard time starting the containers after building the image.

ana@a-MacBook-Air vmc-docker % docker images
REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
vmc                         latest    79d8d7075488   16 hours ago   202MB
vmc-static-nginx            latest    070f0524d523   16 hours ago   25MB
vmc-builder                 latest    e598826c6825   16 hours ago   290MB

**Comment by mwalkowski** [comment]
Hi @jonathangull 

I have just released a developer toolkit for VMC: https://github.com/DSecureMe/vmc-dev-toolkit.

I hope it helps you. If not then don't hesitate to let us know.
