### ISSUE TITLE
Docker container keeps exiting after starting

### ISSUE THREAD

**Issue by ruddymallard** [DSecureMe/vmc-docker#15]
After I pull the image (as stated in the first step), I can't figure out how to get it all to run and stay online via docker. As soon as I run it, it exits with a code 0 - almost as if it just runs as an empty python instance. I'm slightly a newbie at docker so it's probably something I'm neglecting to do.

**Comment by mwalkowski** [comment]
I solved this bug yesterday https://github.com/DSecureMe/vmc-demo/issues/4. Please download the dsecureme/vmc-static-nginx:1.0.2 image again and and let me know if it works.
