### ISSUE TITLE
Demo doesn't run

### ISSUE THREAD

**Issue by FoIsBo** [DSecureMe/vmc-docker#4]
When i try to start command:
`make build`
I get this error:
`=> ERROR [builder 3/3] RUN pip3.6 install --no-cache-dir vmcenter==1.1-RC-1 0.7s` 

what's command pip3.6???

**Comment by mwalkowski** [comment]
Thanks for the information. We are preparing a new release and a demo. I think everything will be ready by the end of the week.

**Comment by FoIsBo** [comment]
In Dockerfile just dell ".6" in line 
`RUN pip3.6 install --no-cache-dir vmcenter==${VMC_VERSION}`
and all seems to be good.


But I have one more Issue - the Kibana can't connect to elastick. 
port :5601 Kibana - doesn't work at all
port :8081 Ralph - work
port :9000 The Hive - connect but many errors and can't login
port :8080 VMC - work and can login but without kibana as i understand there's no base to work whith vuln

**Comment by mwalkowski** [comment]
`port :8080 VMC - work and can login but without kibana as i understand there's no base to work whith vuln` - yes you have right.

We already have a working version. But we are waiting for our client's response to be sure that we have solved all his problems. Then we will release the vmc version.

**Comment by Kraxi** [comment]
@FoIsBo 
We just pushed a new version of our [demo](https://github.com/DSecureMe/vmc-demo). The deployment has been simplified for convenience of all users. Please try again with the new version and let us know if it works.

Appreciate your contributiion!
